# Fabric Properties
# Check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.20

# Mod Properties
mod_version=1.1.0
maven_group=com.teeknox.oreoracle
archives_base_name=ore-oracle

# Dependencies
# Check https://modrinth.com/mod/fabric-api/versions for latest Fabric API
fabric_version=0.158.0+26.2
# Check https://modrinth.com/mod/modmenu/versions for latest Mod Menu
modmenu_version=20.0.1

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
org.gradle.parallel=true
